// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    [Migration("20240827130428_InitialDataSeed")]
    partial class InitialDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LocationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = new Guid("1f7f94b1-9086-4cbc-8305-2cca010aac80"),
                            Latitude = 44.815052209915585,
                            Longitude = 20.500449542006542,
                            UserId = new Guid("ed4b5b0f-ef97-4667-a87c-e0198e187d19")
                        },
                        new
                        {
                            LocationId = new Guid("490b4bb0-74fb-43e4-bcb7-93c87aac84a2"),
                            Latitude = 44.78993044294284,
                            Longitude = 20.385673636593243,
                            UserId = new Guid("3b759e54-64da-41dc-9aca-cde72c844364")
                        },
                        new
                        {
                            LocationId = new Guid("8b11b8ba-9b73-4182-a8a0-af196d5be345"),
                            Latitude = 44.789821451875774,
                            Longitude = 20.367093239820761,
                            UserId = new Guid("cd8431de-7ef3-4bc3-8e40-37a86bff35fb")
                        },
                        new
                        {
                            LocationId = new Guid("09dd9a99-d999-448a-b4b0-8e7a42ab89af"),
                            Latitude = 44.74511396416333,
                            Longitude = 20.497349903979902,
                            UserId = new Guid("07954be9-1416-4c31-8aec-4526d785052f")
                        },
                        new
                        {
                            LocationId = new Guid("66a7a985-adb0-4eaf-acdc-1e0598e66e2d"),
                            Latitude = 44.810617801280273,
                            Longitude = 20.542356854502593,
                            UserId = new Guid("3632ed47-ba65-46d0-b3ba-ec50788933ff")
                        },
                        new
                        {
                            LocationId = new Guid("0b496362-1661-46a7-9296-dadd11449751"),
                            Latitude = 44.739755979736444,
                            Longitude = 20.36428440098209,
                            UserId = new Guid("08b6de12-8c71-494f-8580-bcfa2a3289f5")
                        },
                        new
                        {
                            LocationId = new Guid("cce5ffca-042e-455d-96e0-77bebe5aa8a8"),
                            Latitude = 44.820820150827153,
                            Longitude = 20.484971798441034,
                            UserId = new Guid("f3c88bf5-d54e-4aa2-9edf-6eb19d0f2122")
                        },
                        new
                        {
                            LocationId = new Guid("cb9d8357-7426-4fb1-a511-ffe8ea619b87"),
                            Latitude = 44.771040026023819,
                            Longitude = 20.488791104084296,
                            UserId = new Guid("47858dba-8e9e-41f3-ac6b-956306181751")
                        },
                        new
                        {
                            LocationId = new Guid("6d7b93ec-bede-43d8-bb91-7f59a5bab1a0"),
                            Latitude = 44.835827333430387,
                            Longitude = 20.460244978351422,
                            UserId = new Guid("d42d0995-fa26-4c38-aa5d-b0f412f72aea")
                        },
                        new
                        {
                            LocationId = new Guid("743cf9bc-9f0a-48e3-a6e2-39736e7b73a7"),
                            Latitude = 44.754111100183074,
                            Longitude = 20.45266152470095,
                            UserId = new Guid("4f2a2546-ff08-40cb-8234-d8b03e64f135")
                        },
                        new
                        {
                            LocationId = new Guid("450e4b9f-a99e-4882-bbb7-46b740ea127f"),
                            Latitude = 44.743014464918211,
                            Longitude = 20.519409199056991,
                            UserId = new Guid("a48d09a8-049f-44fa-8a03-68dbdd8cea1d")
                        },
                        new
                        {
                            LocationId = new Guid("0ac1c603-b6c7-48e0-b6c4-0d460a41c919"),
                            Latitude = 44.808743410710903,
                            Longitude = 20.379587718310489,
                            UserId = new Guid("39c4f7a2-6eb4-4716-8b06-c8b9b28fcfe1")
                        },
                        new
                        {
                            LocationId = new Guid("37aad600-9caf-454b-a39e-a5ac98743d0a"),
                            Latitude = 44.777261714064373,
                            Longitude = 20.410337914924423,
                            UserId = new Guid("78cb9f22-4bbf-48ad-b133-e673237cfbaf")
                        },
                        new
                        {
                            LocationId = new Guid("405bcf21-192c-4abb-b29f-f5d8e2b4cfa0"),
                            Latitude = 44.78516158142822,
                            Longitude = 20.470297186766704,
                            UserId = new Guid("a3854e05-28fb-4451-b5a8-386e1f520622")
                        },
                        new
                        {
                            LocationId = new Guid("35755449-236f-48ba-bc7d-f839aa6ac38e"),
                            Latitude = 44.817896763964299,
                            Longitude = 20.494372987074879,
                            UserId = new Guid("de7b5011-ef2d-49a2-99ae-c0f119fc3044")
                        },
                        new
                        {
                            LocationId = new Guid("50191edd-4a5c-441d-a834-432d7f4fc90f"),
                            Latitude = 44.753968612457079,
                            Longitude = 20.454024177400711,
                            UserId = new Guid("4a5bf110-3a98-4c9c-a7a0-2cb84c363168")
                        },
                        new
                        {
                            LocationId = new Guid("b0d7bcb5-d4be-4ce2-b4e4-b6fe24aa6869"),
                            Latitude = 44.788264859529512,
                            Longitude = 20.367158546633799,
                            UserId = new Guid("a86e82fa-622f-4ead-a8f3-8a799be20155")
                        },
                        new
                        {
                            LocationId = new Guid("b83d8ec7-9020-4969-8ed4-3c3635d86521"),
                            Latitude = 44.835509940101872,
                            Longitude = 20.507731048789907,
                            UserId = new Guid("c2053672-96d8-43fb-8641-35436480752e")
                        },
                        new
                        {
                            LocationId = new Guid("cbccd97f-b27c-4135-b654-1ceed33da688"),
                            Latitude = 44.77991543923585,
                            Longitude = 20.452452771930304,
                            UserId = new Guid("1de0ff64-d9d0-4cc4-b53d-7b1231fcdcce")
                        },
                        new
                        {
                            LocationId = new Guid("3620e695-e67b-41fc-800d-df675a7e399a"),
                            Latitude = 44.762168396599861,
                            Longitude = 20.366240887652292,
                            UserId = new Guid("ff5b1fa2-5c4b-4e7a-990f-a8d34f4e6bfe")
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ed4b5b0f-ef97-4667-a87c-e0198e187d19"),
                            Email = "user1@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 2080427802,
                            UserName = "User1"
                        },
                        new
                        {
                            UserId = new Guid("3b759e54-64da-41dc-9aca-cde72c844364"),
                            Email = "user2@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 341851734,
                            UserName = "User2"
                        },
                        new
                        {
                            UserId = new Guid("cd8431de-7ef3-4bc3-8e40-37a86bff35fb"),
                            Email = "user3@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 1431988776,
                            UserName = "User3"
                        },
                        new
                        {
                            UserId = new Guid("07954be9-1416-4c31-8aec-4526d785052f"),
                            Email = "user4@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 1938005744,
                            UserName = "User4"
                        },
                        new
                        {
                            UserId = new Guid("3632ed47-ba65-46d0-b3ba-ec50788933ff"),
                            Email = "user5@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 761513014,
                            UserName = "User5"
                        },
                        new
                        {
                            UserId = new Guid("08b6de12-8c71-494f-8580-bcfa2a3289f5"),
                            Email = "user6@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 2037243568,
                            UserName = "User6"
                        },
                        new
                        {
                            UserId = new Guid("f3c88bf5-d54e-4aa2-9edf-6eb19d0f2122"),
                            Email = "user7@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 1528357293,
                            UserName = "User7"
                        },
                        new
                        {
                            UserId = new Guid("47858dba-8e9e-41f3-ac6b-956306181751"),
                            Email = "user8@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 1311292502,
                            UserName = "User8"
                        },
                        new
                        {
                            UserId = new Guid("d42d0995-fa26-4c38-aa5d-b0f412f72aea"),
                            Email = "user9@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 749943798,
                            UserName = "User9"
                        },
                        new
                        {
                            UserId = new Guid("4f2a2546-ff08-40cb-8234-d8b03e64f135"),
                            Email = "user10@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 319576108,
                            UserName = "User10"
                        },
                        new
                        {
                            UserId = new Guid("a48d09a8-049f-44fa-8a03-68dbdd8cea1d"),
                            Email = "user11@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 2072233842,
                            UserName = "User11"
                        },
                        new
                        {
                            UserId = new Guid("39c4f7a2-6eb4-4716-8b06-c8b9b28fcfe1"),
                            Email = "user12@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 1156976611,
                            UserName = "User12"
                        },
                        new
                        {
                            UserId = new Guid("78cb9f22-4bbf-48ad-b133-e673237cfbaf"),
                            Email = "user13@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 811244070,
                            UserName = "User13"
                        },
                        new
                        {
                            UserId = new Guid("a3854e05-28fb-4451-b5a8-386e1f520622"),
                            Email = "user14@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 1063087737,
                            UserName = "User14"
                        },
                        new
                        {
                            UserId = new Guid("de7b5011-ef2d-49a2-99ae-c0f119fc3044"),
                            Email = "user15@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 2103111965,
                            UserName = "User15"
                        },
                        new
                        {
                            UserId = new Guid("4a5bf110-3a98-4c9c-a7a0-2cb84c363168"),
                            Email = "user16@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 1036067702,
                            UserName = "User16"
                        },
                        new
                        {
                            UserId = new Guid("a86e82fa-622f-4ead-a8f3-8a799be20155"),
                            Email = "user17@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 1929035529,
                            UserName = "User17"
                        },
                        new
                        {
                            UserId = new Guid("c2053672-96d8-43fb-8641-35436480752e"),
                            Email = "user18@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 2137347066,
                            UserName = "User18"
                        },
                        new
                        {
                            UserId = new Guid("1de0ff64-d9d0-4cc4-b53d-7b1231fcdcce"),
                            Email = "user19@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 825105703,
                            UserName = "User19"
                        },
                        new
                        {
                            UserId = new Guid("ff5b1fa2-5c4b-4e7a-990f-a8d34f4e6bfe"),
                            Email = "user20@example.com",
                            PasswordHash = "hashedPassword",
                            Points = 75333798,
                            UserName = "User20"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Location", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("Location")
                        .HasForeignKey("Domain.Entities.Location", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Location")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
